export type AutonomyLevel = "manual" | "workspace" | "build-test" | "full-project";
export type DefaultVisibleMode = "codex-app-visible" | "ghostty-visible";
export type CodexAppServerMode = "disabled" | "manual" | "auto";
export type CodexAppServerTransport = "ws" | "http";

export interface Config {
  port: number;
  controlPort: number;
  ownerDataDir: string;
  relayToken?: string;
  allowUrlTokenAuth: boolean;
  urlToken?: string;
  urlTokenRequiredPrefix: string;
  urlTokenMinLength: number;
  urlTokenExpiresAt?: string;
  disableAuth: boolean;
  developmentMode: boolean;
  allowedRoots: string[];
  defaultParentDir: string;
  publicBaseUrl?: string;
  codexBin: string;
  codexModel?: string;
  terminalApp: string;
  terminalFallbackApp: string;
  preferGhostty: boolean;
  defaultVisibleMode: DefaultVisibleMode;
  codexAppServerMode: CodexAppServerMode;
  codexAppServerUrl?: string;
  codexAppServerPort: number;
  codexAppServerHost: string;
  codexAppServerTransport: CodexAppServerTransport;
  codexAppServerAutostart: boolean;
  codexAppServerLogDir: string;
  codexAppServerAllowPublicHost: boolean;
  codexAppServerIsolateMcpServers: boolean;
  databasePath: string;
  defaultCodexApproval: string;
  defaultCodexSandbox: string;
  allowNetworkCommands: boolean;
  maxCommandOutputBytes: number;
  commandTimeoutMs: number;
  codexTimeoutMs: number;
  requireApprovalForCodexVisible: boolean;
  requireApprovalForCodexHidden: boolean;
  requireApprovalForWriteFile: boolean;
  requireApprovalForNormalCommands: boolean;
  enableExperimentalOAuth: boolean;
  oauthIssuerBaseUrl?: string;
  oauthAccessTokenTtlSeconds: number;
  oauthAuthCodeTtlSeconds: number;
  oauthAllowedRedirectHosts: string[];
  oauthRequireLocalApproval: boolean;
}

export const AUTONOMY_LEVELS: AutonomyLevel[] = ["manual", "workspace", "build-test", "full-project"];
